version: "3"
services:
  backend:
    build: backend/
    hostname: backend
    network_mode: "host"
    depends_on:
      - mongo
  frontend:
    build: frontend/
    network_mode: "host"
  mongo:
    image: mongo
    network_mode: "host"
