version: "3"
services:
  backend:
    build: backend/
    hostname: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  frontend:
    build: frontend/
    ports:
      - "8080:80"
    links:
      - backend
  mongo:
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
